cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'brew-cask'
brew 'openssl'
brew 'readline'
brew 'rbenv'
brew 'ruby-build'

cask 'google-chrome'
cask 'night-owl'
cask 'google-japanese-ime'
cask 'alfred'
cask 'dropbox'
cask 'iterm2'
cask 'silverlight'
